site_name: ASR for Aviation Documentation

repo_url: https://github.com/AVanDeBrook/asr-project

site_author: Aaron Van De Brook

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - json
    - python
    - yaml
