name: GitHub pages automation

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Dependency Setup
        run: |
          pip install -U Cython
          pip install -r requirements/docs_requirements.txt
          pip install -r requirements/requirements.txt

      - name: Sphinx Build
        run: |
          sphinx-build -M html docs/source build

      - name: Upload to gh-pages
        run: |
          ghp-import -p build/html
