name: GitHub pages automation

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Dependency Setup
        run: |
          pip install -r requirements/docs_requirements.txt
          pip install -r requirements/requirements.txt

      - name: Sphinx Build
        run: |
          sphinx-build -M html docs/source .
          mv html/* .

      - name: Post-build Clean Up
        run: |
          rm -r {.github,docs,requirements,source}
          rm {.editorconfig,.gitignore,README.md}

      - name: Deploy to Branch
        run: |
          git checkout -fb gh-pages
          git add . && git commit -m "Rebuild and deploy documentation" && git push -u origin gh-pages
