name: GitHub pages automation

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Documentation Setup
        run: |
          pip install mkdocs
          mkdocs gh-deploy
